# Ref: https://github.com/niccai/zeit-now-with-circleci/blob/develop/.circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/tmp/personal-starter
  parallelism: 1

version: 2
jobs:
  validate:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/personal-starter
      - restore_cache:
          key:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run: npm install
      - run: npm validate
      - run:
        name: push codecoverage
        command: npx codecov
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - persist_to_workspace:
      #   root: .
      #   paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
        at: ~/tmp/personal-starter
      - run: npm build
  staging-release:
    <<: *defaults
    steps:
      - attach_workspace:
        at: ~/tmp/personal-starter
      - run: sudo now install --global --unsafe-perm now
      - deploy:
        command: |
          now --token $ZEIT_TOKEN --local-config .now/now.canary.json
          now --token $ZEIT_TOKEN --local-config .now/now.canary.json alias
  production-release:
    <<: *defaults
    steps:
      - attach_workspace:
        at: ~/tmp/personal-starter
      - run: sudo now install --global --unsafe-perm now
      - deploy:
          name: alias deployments
          command: |
            now --token $ZEIT_TOKEN --local-config .now/now.prod.json
            now --token $ZEIT_TOKEN --local-config .now/now.prod.json alias

workflows:
  version: 2
  deployments:
    jobs:
      - validate
      - build
      # - branch-release:
      # configuration to deploy new now URL per feature
      - staging-release:
        requires:
          - validate
          - build
        filters:
          branches:
            only: master
            tags: /^.*canary.*($|\b)/
      - production-release:
        requires:
          - validate
          - build
        filters:
          branches:
            only: master
            tags: /^(\d+\.)?(\d+\.)?(\*|\d+)$/
